on:
  # Trigger the workflow on push, but only for the dev branch
  push:
    branches:
      - master
name: build-and-deploy

jobs:
  build:
    timeout-minutes: 5
    name: Build & Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'yarn' # Enable Yarn caching
      - name: Install deps
        run: yarn install # will run `yarn install` command
      - name: Build the project
        run: yarn build # will run `yarn build` command
      - name: Run deploy script
        run: |
          git config user.name "kniazevgeny" && git config user.email "eugene.kniazev@gmail.com"
          git checkout --orphan gh-pages
          echo -e "ivankovlab.ru" >> CNAME
          sudo cp ./dist/index.html ./dist/proddg.html
          git --work-tree dist add --all
          git --work-tree dist commit -m gh-pages
          git push origin HEAD:gh-pages --force
